name: 'Create or update a pull request comment'
description: 'Enables you to create or update a pull request comment.'
inputs:
  content:
    description: 'Content of the comment to be posted on PR, may include markdown'
    required: true
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    required: false
    default: ${{ github.token }}
  username:
    description: 'Username of the holder of token, to find and replace the comment'
    required: false
    default: 'github-actions[bot]'
  update-comment:
    description: 'Should the comment be updated on successive runs or a new one created'
    required: false
    default: 'true'
outputs:
  comment-id:
    description: 'Id of the created comment'
runs:
  using: 'node16'
  main: 'index.js'
  pre-if: github.event.name == "pull_request"
