name: 'Create PR comment'
description: 'Greet someone and record the time'
inputs:
  content:
    description: 'Content of the comment to be posted on PR, may include markdown'
    required: true
    default: 'Hello from action!'
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    required: false
    default: ${{ github.token }}
outputs:
  comment_id:
    description: 'Id of the created comment'
runs:
  using: 'node16'
  main: 'index.js'
